
[workspace]
members = [
	'apps/dev-disp-server',
	'libs/dev-disp-comm',
	'libs/dev-disp-core',
	'libs/dev-disp-client-lib',
	'libs/dev-disp-provider-evdi',
	'libs/dev-disp-ws-js', "libs/dev-disp-encoders", "libs/edid", "libs/rust-util",
]
resolver = '3'
